<div class="none"> </div>
	<div class="login_form">		
		<div class="login_holder">
				<div class="login_top">
					Вход в системата
				</div>
				
				<div class="login_mid">
					<form method="post">
						<div class="form-element">
							<div class='label'>
								<label>Потребителско име:</label>
							</div>
							<div class='container'>
								<?=$this->form->username?>
							</div>
						</div>
						<div class="form-element">
							<div class='label'>
								<label>Парола:</label>
							</div>
							<div class='container'>
								<?=$this->form->password?>
							</div>
						</div>
						<div class="form-element">
							<div class='label'></div>
							<div class='container'>
								<input type="submit" value="Вход" class="submit">
							</div>
						</div>
					</form>
				</div>
	</div>
</div>