<!-- Main Section -->

                <section class="main-section grid_7">

                    <div class="main-content">
<header>
	<ul class="action-buttons clearfix fr">
		<li>
			<a href="/" class="button button-gray no-text help" rel="#overlay">
				<span class="help"></span>
			</a>
		</li>
	</ul>
	<div class="view-switcher">
	<h2><?php echo $this->translate('Group')?></h2>
	</div>
</header>
<section>
		<section class="container_4 clearfix">
		<?php if($this->confirm) : ?>
			<div class="message success">
				<?= $this->translate($this->confirm); ?>
			</div>
		<?php endif;?>
		<?php if($this->msg) : ?>
			<div class="message error">
				<?= $this->translate($this->msg); ?>
			</div>
		<?php endif;?>
		<form action="/group/add" class="form" method="post">
		<?= $this->form->groupname; ?>
		<br />
		<?= $this->form->people; ?>
		<label>&nbsp;</label><?= $this->form->login ?>
		
		</form>
</section>
</div>
</section>

