  <style>
/* #google_maps_address a, #google_maps_address span, #google_maps_address div>div>a>div, #google_maps_address div>div.gmnoprint{display: none;} */
 </style>
 <!-- Main Section -->
                <section class="main-section grid_7">
                    <div class="main-content grid_4 alpha">
                        <header class="clearfix">
                        	<?php if($this->company['avatar']):?>
                             <span class="avatar"><img width="55" height="55" src="<?php echo $this->company['avatar']; ?>" /></span>
                             <?php else:?>
                             <span class="avatar"></span>
                             <?php endif;?>
                             <hgroup>
                                 <h2>
                                     <?php echo $this->company['name']?>
                                 </h2>
                                 <div class="display_tags">
                                 <?php if($this->tags):?>
                                 	<?php   foreach ($this->tags as $tag):?>
                                 		<span class="tag"><a href="/contact/sort/tag/<?php echo $tag['id']?>" class="tag"><?php echo $tag['name']?></a><a href="#" style="display:none" class="tag_delete" onclick="removeTag(2,<?php echo $this->company['id']?>,<?php echo $tag['id']?>)">x</a></span>
                                 	<?php endforeach;?>
                                 <?php endif;?>
                                 </div>
                                 <div class="tags">
                                 	<a class="add_tag" onclick="$('.add_tag').toggle(); $('.tag_delete').toggle();"><?php echo $this->translate('Add tag'); ?></a>
                                 </div>
                                 <div class="add_tag" style="display: none;">
                                 	<input type="hidden" value="<?php echo $this->company['id']?>" id="id_ref" name="type" />
                                 	<input type="hidden" value="2" id="tag_type" name="type" />
                                 	<input type="text" name="tag" id="tag" />
                                 	<input type="button" name="submit" id="tag_submit" value="<?php echo $this->translate('Add'); ?>" />
                                 	<input type="button" name="submit" id="tag_close" value="<?php echo $this->translate('Close'); ?>" />
                                 </div>
                             </hgroup>
                        </header>
                        <section>
                        	<table class="tabs">
                        		<thead></thead>
                        		<tbody>
	                        		<tr>
	                        			<td><a onclick="showNotes()" class="active" style="cursor:pointer;"><?php echo $this->translate('Notes'); ?></a></td>
	                        			<td><a onclick="showPeople()" style="cursor:pointer;"><?php echo $this->translate('People'); ?> (<?php echo count($this->countPpl); ?>)</a></td>
	                        		</tr>
                        		</tbody>
                        	</table>
                        <div class="notes">
<!-- Начало на формата  -->
                            <form method="post" action="/contact/companyrecord/id/<?php echo $this->company['id']?>" enctype="multipart/form-data">
                           		<input type="hidden" name="id_company" value="<?php echo $this->company['id']?>" />
                                 <textarea class="markItUpTextarea" name="note" style="min-height: 50px; max-height: 50px; width: 100%;"></textarea>
                                 
                                <a class="toggle-file" style="cursor: pointer;"><b><?php echo $this->translate('Attach file'); ?></b></a>
	                        	<div class="file-wrap" style="display:none;">
	                        		<br />
	                        		<input id="file" type="file"  name="file" />
	                        		<img class="add-file" src="/images/icons/add.png" />
	                        	</div>
	                        	<div class="file-wrap" style="display:none;">
	                        		<br />
	                        		<b><?php echo $this->translate('Attach this note to a case'); ?></b>
	                        		<br />
	                        		<select name="id_case" id="case_select">
	                        				<option value=""></option>
	                        			<?php if($this->projects):?>
	                        				<?php foreach ($this->projects as $project):?>
	                        					<option value="<?php echo $project['id']?>"><?php echo $project["name"] ?></option>
	                        				<?php endforeach;?>
	                        			<?php endif;?>
	                        		</select>
	                        		<br />
	                        		<br />
	                        		<b><?php echo $this->translate('Who can see this note?'); ?></b>
	                        		<br />
	                        		<input type="radio" class="radio" name="access" value="0" checked /> 
									<label class="radio"><?php echo $this->translate('Everyone'); ?></label><br />
									<input type="radio" class="radio" name="access" value="1" />
									<label class="radio"> <?php echo $this->translate('Only me'); ?></label><br />
									<input id="radioGroup" class="radio" type="radio" name="access" value="2"  />
									<label class="radio"><?php echo $this->translate('Me and this group'); ?></label>
									<select id="group_select" name="group">
                        				<?php foreach ($this->groups as $project):?>
                        					<option value="<?php echo $project['id']?>"><?php echo $project["name"] ?></option>
                        				<?php endforeach;?>
                        			</select>
                        			<br />
	                        		<br />
	                        		<b><?php echo $this->translate('When did it happen?'); ?></b>
	                        		<br />
									<input type="date" class="date" name="when">
	                        		<br />
	                        		<br />
	                        		<b><?php echo $this->translate('Email this note'); ?></b>
	                        		<br />
	                        		<?php foreach ($this->profiless as $project):?>
	                        					<input type="checkbox" name="prfile[]" value="<?php echo $project['id']?>" /> <?php echo $project["firstname"] ?> <span class="label"><?php echo $project["lastname"] ?></span><br />
	                        		<?php endforeach;?>
	                        	</div>
                                 <input type="submit" value="<?php echo $this->translate('Add Note');?>" class="fr button button-gray"></input>
                            </form>
 <!-- Край на формата  -->  
                            <div class="clear"></div>
                               <h3><?php echo $this->translate('Latest');?></h3>
	                           	    <ul class="listing list-view">
                            <?php // Zend_Debug::dump($this->data);die;?>
                            <?php foreach($this->notes as $note):?>
                            	<?php $note['avatar'] = $note['avatar']?$note['avatar']:'/images/user_32.png'; ?>
                                 <li class="note" id="<?php echo $note['id']?>">
                                 	<div style="float:left; margin-right: 10px;">
                                 		<img width="55" height="55" src="<?php echo $note["avatar"]; ?>"/>
                                 	</div>	
                                 	<?php  if(isset($note["personfirstname"]) && $note["personfirstname"]):?>
                                    	<a href="/contact/personrecord/id/<?php echo $note['id_person']?>"> 
                                    		<?php  echo $note['personfirstname']?> 
                                    		<?php  echo $note['personlastname']?>
                                    	</a>
                                	<?php  elseif(isset($note["case"]) && $note["case"]):?>
                                		<a href="/project/record/id/<?php echo $note['id_case']?>">
                                			<?php  echo $note['case']?>
                                		</a>
                                    <?php  elseif(isset($note["company"]) && $note["company"]):?>
                                    	<a href="/contact/companyrecord/id/<?php echo $note['id_company']?>">
                                    		<?php  echo $note['company']?>
                                    	</a>
                                    <?php  endif;?> 
                                     <span class="timestamp">
                                    	<a href="/index/comment/id/<?php echo $note['id']?>">
                                    		<img src="/images/icons/comment.png"/>
                                    	</a>
                                    	<?php if($this->profile->admin == 1 || $this->profile->id == $note['author']):?>
	                                    	<a class="fancybox" href="/index/editfancynote/id/<?php echo $note['id']?>"><img class="" src="/images/icons/pencil.png"/></a>
	                                    	<a onclick="deleteNote(<?php echo $note['id']?>)"><img id="<?php echo $note['id']?>" class="delete_note" src="/images/icons/delete.png"/></a><br/>
                                     	<?php endif; ?>
                                     </span>
                                    <br />
                                    <span class="timestamp_left">
                                    	<b><?php if($note['when']) {echo $this->translate(date("D", strtotime($note['when']))); echo ', '.$this->translate(date("M", strtotime($note['when']))); echo ' '.date("j Y", strtotime($note['when'])); } else { echo $this->translate(date("D", strtotime($note['cdate']))); echo ', '.$this->translate(date("M", strtotime($note['cdate']))); echo ' '.date("j Y", strtotime($note['cdate']));}?></b><br/>
                                    </span>
                                    <div class="entry-meta">
                                       <?php echo $note['profile']?>
                                    </div>
                                    <p><?php echo $note['note']?></p>
                                     <div class="file-meta">
                                        <?php if($note['files']):?>
                                        	<?php foreach ($note['files'] as $file):?>
                                        		<?php if($file['type'] == 1):?>
                                        			<a href="<?php echo $file['file']; ?>"><img width="50" height="50" src="<?php echo $file['file']; ?>"/></a>
                                        		<?php elseif ($file['type'] == 2):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/pdf.png"/></a>
                                        		<?php elseif ($file['type'] == 3):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/xls.png"/></a>
                                        		<?php elseif ($file['type'] == 4):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/doc.png"/></a>
                                        		<?php elseif ($file['type'] == 5):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/ppt.png"/></a>
                                        		<?php else:?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/icons/page.png"/></a>
                                        		<?php endif;?>
                                        	<?php endforeach;?>
                                        <?php endif;?>
                                    </div>
                                </li>
                             <?php endforeach;?>
                            </ul>
	                            <div class="gimmimoar">
	                            	<?php echo $this->translate('Show older'); ?>
	                            </div>
	                       </div>     
                        </section>
                    </div>
                    <div class="preview-pane grid_3 omega">
                        <div class="content">
                        	 <h3><?php echo $this->translate('Add new task about ');?> <?php echo $this->company['name']?>
                                 <br />
                                 <a  class="button has-popupballoon" >
                                 	<?php echo $this->translate('Add task');?>
                                 </a>
                                 <div class="popupballoon top">
	                            	<div id="taskForm">
		                                <h3><?php echo $this->translate('Task about ');?>  <?php echo $this->company['name']?></h3>
		                                <input type="text" id="tasknameC" /><br /><br />
		                                <?php echo $this->translate('When it\'s due?');?><br />
		                                <input type="date" id="taskdueC" /><br />
		                                 <?php echo $this->translate('Who\'s the owner?' );?><br />
		                                <select  id="ownerC" >
		                                	<?php if($this->profiless)
		                                	{
		                                		foreach ($this->profiless as $key=>$prof)
		                                		{
		                                			echo '<option value="'.$prof['id'].'">'.$prof['firstname'].' '.$prof['lastname'].'</option>';
		                                		}
		                                	}else{
		                                		
		                                	}?>
		                                </select>
		                                 <?php echo $this->translate('What category?');?><br />
		                                <select id="taskCatC">
		                                	<?php if($this->cats)
		                                	{
		                                		foreach ($this->cats as $cat)
		                                		{
		                                			echo '<option value="'.$cat['id'].'">'.$this->translate($cat['name']).'</option>';
		                                		}
		                                	}else{
		                                		
		                                	}?>
		                                </select>
		                                <hr />
		                                <br />
		                                <a onclick="addTaskC()" id="addTaskC" class="button button-orange">  <?php echo $this->translate('Add task');?></a>
		                                <button class="button button-gray close"><?php echo $this->translate('Cancel');?></button>
	                            	</div>
	                            </div>
                           	 </h3>
                           	 
                            <h3><?php echo $this->translate('Contacts');?>
                           		<ul class="action-buttons clearfix fr">
                                   <li><a href="/contact/editcompany/id/<?php echo $this->company['id']?>" class="button" rel="#overlay"><span class="edit"><img src="/images/icons/pencil.png"/></span></a></li>
                            	</ul>
                            </h3>
                            <ul class="profile-info">
                            <?php if(isset($this->company['phone']) && $this->company['phone']):?>
                           		<li class="mobile"><?php echo $this->company['phone']; ?><span><?php echo $this->translate('phone')?></span></li>
                            <?php endif;?>
                            <?php if(is_array($this->phones)):?>
	                            <?php foreach($this->phones as $phone):?>
	                                <li class="mobile"><?php echo $phone['phone']; ?><span><?php echo $this->translate('phone')?></span></li>
	                            <?php endforeach;?>
                            <?php endif;?>
                            <?php if(isset($this->company['email']) && $this->company['email']):?>
                            	<li class="email">
                            		<a href="mailto:<?php echo $this->company['email']; ?>?bcc=<?php echo $this->emailname; ?><?php echo $this->company['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">
                            			<?php echo $this->company['email']; ?>
                            		</a> 
                            		<span>
                            			<?php echo $this->translate('email')?>
                            		</span>
                            	</li>
                            <?php endif;?>
                            <?php if(is_array($this->emails)):?>
	                            <?php foreach($this->emails as $phone):?>
	                                <li class="email">
	                                	<a href="mailto:<?php echo $phone['name']; ?>?bcc=<?php echo $this->emailname; ?><?php echo $this->company['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">
                            				<?php echo $phone['name']; ?>
                            			</a> 
	                                	<span>
	                                		<?php echo $this->translate('address')?>
	                                	</span>
	                                </li>
	                            <?php endforeach;?>
                            <?php endif;?>
                            <?php if(isset($this->company['website']) && $this->company['website']):?>
                            	<li class="website">
                            		<a target="_blank" href="http://<?php echo $this->company['website']; ?>" >
                            			<?php echo $this->company['website']; ?>
                            		</a>
                            		<span>
                            			<?php echo $this->translate('website')?>
                            		</span>
                            	</li>
                            <?php endif;?>
                            <?php if(is_array($this->websites)):?>
	                            <?php foreach($this->websites as $phone):?>
	                                <li class="website">
	                                	<a target="_blank" href="http://<?php echo $phone['name']; ?>" >
	                                		<?php echo $phone['name']; ?>
	                                	</a>
	                                	<span>
	                                		<?php echo $this->translate('website')?>
	                                	</span>
	                                </li>
	                            <?php endforeach;?>
	                        <?php endif;?>
	                        <?php if(isset($this->company['address']) && $this->company['address']):?>
                            	<li class="email"><?php echo $this->company['address']; ?><span><?php echo $this->translate('address')?></span></li>
                            	<?php if(is_array($this->addresses)):?>
		                            <?php foreach($this->addresses as $phone):?>
		                                <li class="email"><?php echo $phone['address']; ?><span><?php echo $this->translate('address')?></span></li>
		                            <?php endforeach;?>
	                       		 <?php endif;?>
	                          <div id="google_maps_address" style="width: 98%; height:200px; margin: 2px auto;"></div>
	                        <?php endif;?>
	                        <?php if($this->additional):?>
	                        	<?php foreach ($this->additional as $field):?>
	                        		<?php if(isset($this->company[$field['name']]) && $this->company[$field['name']]):?>
	                        			<li class=""><?php echo $this->company[$field['name']]; ?><span><?php echo $this->translate($field['label'])?></span></li>
	                        		<?php endif;?>
	                        	<?php endforeach;?>
	                        <?php endif;?>
                            </ul>
                        </div>
                    </div>
                </section>
                <!-- Main Section End -->
                
<script type="text/javascript">
$(function(){
	var data = new Object();
	data.count = 1;
	data.location = 'companyrecord';
	data.id = <?php echo $this->company['id']?>;

	
	$('.gimmimoar').mouseover(
		function(){
			data =  addNotes(data);
		}
	);

	$(window).scroll(function() {   
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 10) {
			 data =  addNotes(data);
		   }
	});
	$('#google_maps_address').gmap3(
			{
				 map: {
				    options: {
				      maxZoom: 14 
				    }  
				 },
				 marker:{
				    address: <?php echo Zend_Json::encode($this->company['address']);?>,//company['company']['0'].country+' '+company['company']['0'].city+' '+ company['company']['0'].address,
				    options: {
				     icon: new google.maps.MarkerImage(
				       "/images/icons/arrow_down.png",
				       new google.maps.Size(32, 37, "px", "px")
				     )
				    }
				 }
				},
				"autofit" 
	);

	addToLastviewed(1, <?php echo $this->company['id']?>);
});

function showPeople()
{
	data = new Object();
	data.id = <?php echo $this->company['id'];?>;
	$('div.notes').hide();
	$.sajax("/contact/companyrecordp",data,function(newdata)
	{
		//console.dir(newdata);
		
		var ul = $('<ul id="contacts" class="list-view clearfix"></ul>');
		
		$.each(newdata, function(pi,pv){

			pv.phone = pv.phone==null?'':pv.phone;
			pv.email = pv.email==null?'':pv.email;

			var li = $('<li class="contact clearfix"></li>');
			var divA = $('<div class="avatar"><img src="/images/user_32.png" /></div>');
			var aName = $('<a  class="name"></a>');
			var divEM = $('<div class="entry-meta"></div>');
			var aEdit = $('<a><img src="/images/icons/pencil.png" /></a>');
			var aDelete = $('<a ><img src="/images/icons/delete.png" /></a>');
			
			
			li.append(divA);
			aName.attr('href', '/contact/personrecord/id/'+pv.id);
			aName.html(pv.name);
			li.append(aName);
			var spanC = $('<div class="meta"><a href="mailto:'+pv.email+'?bcc=<?php echo $this->emailname; ?><?php echo $this->company['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">'+pv.email+'</a> '+pv.phone+'</div>');
			li.append(spanC);
			aEdit.attr('href','/contact/editperson/id/'+pv.id);
			aDelete.attr('href','/contact/deleteperson/id/'+pv.id);
			divEM.html('');
			divEM.append(aEdit);
			divEM.append(aDelete);
			li.append(divEM);
			ul.append(li);
		});
		
		$('table.tabs').after(ul);
		
	});
	$('ul#contacts').remove();
	$('table.tabs a').removeClass('active');
	$('table.tabs a:last').addClass('active');
}

function showNotes()
{	
	$('ul#contacts').remove();
	$('table.tabs a').removeClass('active');
	$('table.tabs a:first').addClass('active');
	$('div.notes').show();
}

function addTaskC()
{	
	
	sdata = new Object();
	sdata.id_company = '<?php echo $this->company['id']; ?>';
	sdata.name = $('input#tasknameC').val();
	sdata.owner = $('select#ownerC').val();
	sdata.due = $('input#taskdueC').val();
	sdata.cat = $('select#taskCatC').val();
	sdata.publ = 1;
	if(sdata.name != '' && sdata.due != "" && sdata.cat != "")
	{
		$.sajax("/task/add",sdata, function(newdata){
			if(newdata.id){
				$('.popupballoon').fadeOut(); 
			}
			
		});
	};
};

</script>
<script type="text/javascript"src="/js/gmap3.js"></script>
<script type="text/javascript"src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>