<style>
	table.excel_table
	{
		width: 100%; 
		margin: 1em 0;
	}
	table.excel_table td
	{
		border: 1px solid #ccc;
		padding: 2px;
	}
	table.excel_table tbody tr:first-child td
	{
		font-weight: bold;
		text-align: center;
	}
	table.excel_table tbody tr:first-child td:first-child
	{
		font-weight: normal;
		text-align: left;
	}
	table.excel_table td:first-child
	{
		border-top: 0;
		border-left: 0;
		border-bottom:1px solid #ccc;
		border-right:1px solid #ccc;
		padding: 2px;
		background: #eee;
	}
	table.excel_table th
	{	
		border: 1px solid #ccc;
		border-top: 0;
		padding: 2px;
		font-weight: normal;
		background: #eee;
	}
	table.excel_table th:first-child
	{
		border-top: 0;
		border-left: 0;
		border-bottom:1px solid #ccc;
		border-right:1px solid #ccc;
		padding: 2px;
	}
</style>
<section class="main-section grid_7">
	<div class="main-content grid_5 alpha">
		<header>
			<ul class="action-buttons clearfix fr">
			</ul>
				<h2><?php echo $this->translate('Import'); ?></h2>
		</header>
		 <section>
		<p> <?php echo $this->translate('Excel_Import_1'); ?> </p>
		 	<table class="excel_table">
		 		<thead>
		 			<tr>
		 				<th></th>
		 				<th>
		 					<?php echo $this->translate('A'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('B'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('C'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('D'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('E'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('F'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('G'); ?>
		 				</th>
		 			</tr>
		 		</thead>
		 		<tbody>
		 			<tr>
		 				<td>1</td>
		 				<td>
		 					<?php echo $this->translate('Company'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Firstname'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Lastname'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website'); ?>
		 				</td>
		 			</tr>
		 			<tr>
		 				<td>2</td>
		 				<td>
		 					<?php echo $this->translate('Company 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Firstname 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Lastname 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website 1'); ?>
		 				</td>
		 			</tr>
		 			<tr>
		 				<td>3</td>
		 				<td>
		 					<?php echo $this->translate('Company 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Firstname 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Lastname 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email 2'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website 2'); ?>
		 				</td>
		 			</tr>
		 			<tr>
		 				<td>4</td>
		 				<td>
		 					<?php echo $this->translate('Company 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Firstname 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Lastname 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email 3'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website 3'); ?>
		 				</td>
		 			</tr>
		 		</tbody>
		 	</table>
		 	<p>
		 		<?php echo $this->translate('Excel_Import_2'); ?>
		 	</p>
		 		<table class="excel_table">
		 		<thead>
		 			<tr>
		 				<th></th>
		 				<th>
		 					<?php echo $this->translate('A'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('B'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('C'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('D'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('E'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('F'); ?>
		 				</th>
		 				<th>
		 					<?php echo $this->translate('G'); ?>
		 				</th>
		 			</tr>
		 			
		 		<tbody>
		 			<tr>
		 				<td>1</td>
		 				<td>
		 					<?php echo $this->translate('Company'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Firstname'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Lastname'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website'); ?>
		 				</td>
		 			</tr>
		 		</thead>
		 			<tr>
		 				<td>2</td>
		 				<td>
		 					<?php echo $this->translate('Company "n"'); ?>
		 				</td>
		 				<td>
		 				</td>
		 				<td>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Address 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Phone 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('Email 1'); ?>
		 				</td>
		 				<td>
		 					<?php echo $this->translate('website 1'); ?>
		 				</td>
		 			</tr>
		 		</tbody>
		 	</table>
		 	<form action="/contact/import" enctype="multipart/form-data" method="post">
		 		<?php echo $this->form->excel;	?>
		 		<br />
		 		<br />
		 		<?php echo $this->form->save;	?>
		 	</form>
			
		 <section>
	</div>
</section>