 <style>
/* #google_maps_address a, #google_maps_address span, #google_maps_address div>div>a>div, #google_maps_address div>div.gmnoprint{display: none;} */
 </style>
 <!-- Main Section -->

                <section class="main-section grid_7">

                    <div class="main-content grid_4 alpha">
                        <header class="clearfix">
                             <?php if($this->person['company']['avatar']):?>
                             <span class="avatar"><img width="55" height="55" src="<?php echo $this->person['company']['avatar']; ?>" /></span>
                             <?php else:?>
                             <span class="avatar"></span>
                             <?php endif;?>
                             <hgroup>
                                 <h2>
                                     <?php echo $this->person['firstname']?> <?php echo $this->person['lastname']?>
                                 </h2>
                                 <h4><a href="#"> <?php echo $this->person['title']?></a> <?php echo $this->translate('at'); ?> <a href="/contact/companyrecord/id/<?php echo $this->person['company']['id']?>"> <?php echo $this->person['company']['name']?></a></h4>
                             	  <div class="display_tags">
                                 <?php if($this->tags):?>
                                 	<?php   foreach ($this->tags as $tag):?>
                                 		<span class="tag"><a href="/contact/sort/tag/<?php echo $tag['id']?>" class="tag"><?php echo $tag['name']?></a> <a href="#" class="tag_delete"  style="display:none" onclick="removeTag(1,<?php echo $this->person['id']?>,<?php echo $tag['id']?>)"> x</a></span>
                                 	<?php endforeach;?>
                                 <?php endif;?>
                                 </div>
                                 <div class="tags">
                                 	<a class="add_tag" onclick="$('.add_tag').toggle(); $('.tag_delete').toggle();"><?php echo $this->translate('Add tag'); ?></a>
                                 </div>
                                 <div class="add_tag" style="display: none;">
                                 	<input type="hidden" value="<?php echo $this->person['id']?>" id="id_ref" name="type" />
                                 	<input type="hidden" value="1" id="tag_type" name="type" />
                                 	<input type="text" name="tag" id="tag" />
                                 	<input type="button" name="submit" id="tag_submit" value="<?php echo $this->translate('Add'); ?>" />
                                 	<input type="button" name="submit" id="tag_close" value="<?php echo $this->translate('Close'); ?>" />
                                 </div>
                             </hgroup>
                        </header>
                        <section>
<!-- Начало на формата  -->
                            <form method="post" action="/contact/personrecord/id/<?php echo $this->person['id']?>" enctype="multipart/form-data">
                           		 <input type="hidden" name="id_person" value="<?php echo $this->person['id']?>" />
                                 <input type="hidden" name="id_company" value="<?php echo $this->person['company']['id']?>" />
                                 <textarea class="markItUpTextarea" name="note" style="min-height: 50px; max-height: 50px; width: 100%;"></textarea>
                                 
                                <a class="toggle-file" style="cursor: pointer;"><b><?php echo $this->translate('Attach file'); ?></b></a>
	                        	<div class="file-wrap" style="display:none;">
	                        		<br />
	                        		<input id="file" type="file"  name="file" />
	                        		<img class="add-file" src="/images/icons/add.png" />
	                        	</div>
	                        	<div class="file-wrap" style="display:none;">
	                        		<br />
	                        		<b><?php echo $this->translate('Attach this note to a case'); ?></b>
	                        		<br />
	                        		<select name="id_case" id="case_select">
	                        				<option value=""></option>
	                        			<?php if($this->projects):?>
	                        				<?php foreach ($this->projects as $project):?>
	                        					<option value="<?php echo $project['id']?>"><?php echo $project["name"] ?></option>
	                        				<?php endforeach;?>
	                        			<?php endif;?>
	                        		</select>
	                        		<br />
	                        		<br />
	                        		<b><?php echo $this->translate('Who can see this note?'); ?></b>
	                        		<br />
	                        		<input type="radio" class="radio" name="access" value="0" checked /> 
									<label class="radio"><?php echo $this->translate('Everyone'); ?></label><br />
									<input type="radio" class="radio" name="access" value="1" />
									<label class="radio"> <?php echo $this->translate('Only me'); ?></label><br />
									<input id="radioGroup" class="radio" type="radio" name="access" value="2"  />
									<label class="radio"><?php echo $this->translate('Me and this group'); ?></label>
									<select id="group_select" name="group">
                        				<?php foreach ($this->groups as $project):?>
                        					<option value="<?php echo $project['id']?>"><?php echo $project["name"] ?></option>
                        				<?php endforeach;?>
                        			</select>
                        			<br />
	                        		<br />
	                        		<b><?php echo $this->translate('When did it happen?'); ?></b>
	                        		<br />
									<input type="date" class="date" name="when">
	                        		<br />
	                        		<br />
	                        		<b><?php echo $this->translate('Email this note'); ?></b>
	                        		<br />
	                        		<?php foreach ($this->profiless as $project):?>
	                        					<input type="checkbox" name="prfile[]" value="<?php echo $project['id']?>" /> <?php echo $project["firstname"] ?> <span class="label"><?php echo $project["lastname"] ?></span><br />
	                        		<?php endforeach;?>
	                        	</div>
                                 <input type="submit" value="<?php echo $this->translate('Add Note');?>" class="fr button button-gray"></input>
                            </form>
 <!-- Край на формата  -->
                            <div class="clear"></div>
                            <h3><?php echo $this->translate('Latest');?></h3>
                               <ul class="listing list-view">
                            <?php // Zend_Debug::dump($this->data);die;?>
                            <?php foreach($this->notes as $note):?>
                            	
                                 <li class="note" id="<?php echo $note['id']?>">
                                 <?php if($note['avatar']): ?>
                                 	<div style="float:left; margin-right: 10px;">
                                 		<img width="55" height="55" src="<?php echo $note["avatar"]; ?>"/>
                                 	</div>	
                                 	<?php endif;?>
                                	<?php if(isset($note["personfirstname"]) && $note["personfirstname"]):?>
                                    <!--  	<a href="/contact/personrecord/id/<?php echo $note['id_person']?>"> 
                                    		<?php // echo $note['personfirstname']?> 
                                    		<?php //echo $note['personlastname']?>
                                    	</a>
                                    	<?php // echo $this->translate('from');?>
                                    	<a href="/contact/companyrecord/id/<?php echo $note['id_company']?>" ><?php // echo $note["company"]?></a> -->
                                	<?php elseif(isset($note["case"]) && $note["case"]):?>
                                		<a href="/project/record/id/<?php echo $note['id_case']?>">
                                			<?php echo $note['case']?>
                                		</a>
                                    <?php elseif(isset($note["company"]) && $note["company"]):?>
                                    	<a href="/contact/companyrecord/id/<?php echo $note['id_company']?>">
                                    		<?php echo $note['company']?>
                                    	</a>
                                    <?php endif;?>
                                     <span class="timestamp">
                                    	<a href="/index/comment/id/<?php echo $note['id']?>">
                                    		<img src="/images/icons/comment.png"/>
                                    	</a>
                                    	<?php if($this->profile->admin == 1 || $this->profile->id == $note['author']):?>
	                                    	<a class="fancybox" href="/index/editfancynote/id/<?php echo $note['id']?>"><img class="" src="/images/icons/pencil.png"/></a>
	                                    	<a onclick="deleteNote(<?php echo $note['id']?>)"><img id="<?php echo $note['id']?>" class="delete_note" src="/images/icons/delete.png"/></a><br/>
                                     	<?php endif; ?>
                                     </span>
                                    <span class="timestamp_left_big">
                                    	<b><?php if($note['when']) {echo $this->translate(date("D", strtotime($note['when']))); echo ', '.$this->translate(date("M", strtotime($note['when']))); echo ' '.date("j Y", strtotime($note['when'])); } else { echo $this->translate(date("D", strtotime($note['cdate']))); echo ', '.$this->translate(date("M", strtotime($note['cdate']))); echo ' '.date("j Y", strtotime($note['cdate']));}?></b><br/>
                                    </span>
                                    <div class="entry-meta">
                                       <?php echo $note['profile']?>
                                    </div>
                                    <p><?php echo $note['note']?></p>
                                    <div class="file-meta">
                                       	<?php if($note['files']):?>
                                        	<?php foreach ($note['files'] as $file):?>
                                        		<?php if($file['type'] == 1):?>
                                        			<a href="<?php echo $file['file']; ?>"><img width="50" height="50" src="<?php echo $file['file']; ?>"/></a>
                                        		<?php elseif ($file['type'] == 2):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/pdf.png"/></a>
                                        		<?php elseif ($file['type'] == 3):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/xls.png"/></a>
                                        		<?php elseif ($file['type'] == 4):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/doc.png"/></a>
                                        		<?php elseif ($file['type'] == 5):?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/docIcons/ppt.png"/></a>
                                        		<?php else:?>
                                        			<a href="<?php echo $file['file']; ?>"><img src="/images/icons/page.png"/></a>
                                        		<?php endif;?>
                                        	<?php endforeach;?>
                                        <?php endif;?>
                                    </div>
                                </li>
                             <?php endforeach;?>
                            </ul>
                            <div class="gimmimoar">
	                            	<?php echo $this->translate('Show older'); ?>
	                            </div>
                        </section>
                    </div>

                    <div class="preview-pane grid_3 omega">
                        <div class="content">
                        	 <h3><?php echo $this->translate('Add new task about');?> <?php echo $this->person['firstname']?> <?php echo $this->person['lastname']?>
                                 <a  class="button has-popupballoon" >
                                 	<?php echo $this->translate('Add task');?>
                                 </a>
                                 <div class="popupballoon top">
	                            	<div id="taskForm">
		                                <h3><?php echo $this->translate('Task about');?>  <?php echo $this->person['firstname']?> <?php echo $this->person['lastname']?></h3>
		                                <input type="text" id="tasknameP" /><br /><br />
		                                <?php echo $this->translate('When it\'s due?');?><br />
		                                <input type="date" id="taskdueP" /><br />
		                                 <?php echo $this->translate('Who\'s the owner?' );?><br />
		                                <select  id="ownerP" >
		                                	<?php if($this->profiless)
		                                	{
		                                		foreach ($this->profiless as $key=>$prof)
		                                		{
		                                			echo '<option value="'.$prof['id'].'">'.$prof['firstname'].' '.$prof['lastname'].'</option>';
		                                		}
		                                	}else{
		                                		
		                                	}?>
		                                </select>
		                                 <?php echo $this->translate('What category?');?><br />
		                                <select id="taskCatP">
		                                	<?php if($this->cats)
		                                	{
		                                		foreach ($this->cats as $cat)
		                                		{
		                                			echo '<option value="'.$cat['id'].'">'.$this->translate($cat['name']).'</option>';
		                                		}
		                                	}else{
		                                		
		                                	}?>
		                                	
		                                </select>
		                                <hr />
		                                <br />
		                                <a onclick="addTaskP()" id="addTaskP" class="button button-orange">  <?php echo $this->translate('Add task');?></a>
		                                <button class="button button-gray close"><?php echo $this->translate('Cancel');?></button>
	                            	</div>
	                            </div>
                           	 </h3>
                        
                            <h3><?php echo $this->translate('Personal contact');?>
                            	<ul class="action-buttons clearfix fr">
                                   <li><a href="/contact/editperson/id/<?php echo $this->person['id']?>" class="button" rel="#overlay"><span class="edit"><img src="/images/icons/pencil.png"/></span></a></li>
                                </ul>
                            </h3>
                            <ul class="profile-info">
                            <?php if(isset($this->person['phone1']) && $this->person['phone1']):?>
                            	<li class="mobile"><?php echo $this->person['phone1']; ?> <span><?php echo $this->translate('phone')?></span></li>
                            <?php endif;?>
                            <?php if(is_array($this->phones)):?>
	                            <?php foreach($this->phones as $phone):?>
	                                <li class="mobile"><?php echo $phone['phone']; ?><span><?php echo $this->translate('phone')?></span></li>
	                            <?php endforeach;?>
                            <?php endif;?>
                            <?php if(isset($this->person['email']) && $this->person['email']):?>
                            	<li class="email">
	                            	 
	                            	 <a href="mailto:<?php echo $this->person['email']; ?>?bcc=<?php echo $this->emailname; ?><?php echo $this->person['company']['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">
                            				<?php echo $this->person['email']; ?>
                            		</a> 
	                            	<span>
	                            		<?php echo $this->translate('email')?>
	                            	</span>
                            	</li>
                            <?php endif;?>
                            <?php if(is_array($this->emails)):?>
	                            <?php foreach($this->emails as $phone):?>
	                                <li class="email">
		                                <a href="mailto:<?php echo $phone['name']; ?>?bcc=<?php echo $this->emailname; ?><?php echo $this->emailname; ?><?php echo $this->person['company']['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">
                            				<?php echo $phone['name']; ?>
                            			</a> 
	                                	<span>
	                                		<?php echo $this->translate('address')?>
	                                	</span>pan>
	                                </li>
	                            <?php endforeach;?>
                            <?php endif;?>
                             <?php if(isset($this->person['website']) && $this->person['website']):?>
                            	<li class="website">
                            		<a target="_blank" href="http://<?php echo $this->person['website']; ?>" >
                            			<?php echo $this->person['website']; ?>
                            		</a>
                            		<span>
                            			<?php echo $this->translate('website')?>
                            		</span>
                            	</li>
                            <?php endif;?>
                            <?php if(is_array($this->websites)):?>
	                            <?php foreach($this->websites as $phone):?>
	                                <li class="website">
	                                	<a target="_blank" href="http://<?php echo $phone['name']; ?>" >
	                                		<?php echo $phone['name']; ?>
	                                	</a>
	                                	<span>
	                                		<?php echo $this->translate('website')?>
	                                	</span>
	                                </li>
	                            <?php endforeach;?>
	                        <?php endif;?>
	                        <?php if(isset($this->person['address']) && $this->person['address']):?>
                            	<li class="email"><?php echo $this->person['address']; ?> <span><?php echo $this->translate('address')?></span></li>
                            <?php endif;?>
                            <?php if(is_array($this->addresses)):?>
	                            <?php foreach($this->addresses as $phone):?>
	                                <li class="email"><?php echo $phone['address']; ?><span><?php echo $this->translate('address')?></span></li>
	                            <?php endforeach;?>
	                            	
	                        <?php endif;?>
	                        <div id="google_maps_address" style="width: 98%; height:200px; margin: 2px auto;"></div>
	                        
	                         <?php if($this->additional):?>
	                        	<?php foreach ($this->additional as $field):?>
	                        		<?php if(isset($this->person[$field['name']]) && $this->person[$field['name']]):?>
	                        			<li class=""><?php echo $this->person[$field['name']]; ?><span><?php echo $this->translate($field['label'])?></span></li>
	                        		<?php endif;?>
	                        	<?php endforeach;?>
	                        <?php endif;?>
                           </ul>
                           
                           <h3> <?php echo $this->person['company']['name']?> <?php echo $this->translate('contact information');?>
                            	<ul class="action-buttons clearfix fr">
                                   <li><a href="/contact/editcompany/id/<?php echo $this->person['company']['id']?>" class="button" rel="#overlay"><span class="edit"><img src="/images/icons/pencil.png"/></span></a></li>
                                </ul>
                            </h3>
                            <ul class="profile-info">
                                 	<?php if(isset($this->person['company']['phone']) && $this->person['company']['phone']):?>
		                            	<li class="mobile"><?php echo $this->person['company']['phone']; ?> <span><?php echo $this->translate('phone')?></span></li>
		                            <?php endif;?>
		                            <?php if(isset($this->person['company']['email']) && $this->person['company']['email']):?>
		                            	<li class="email">
		                            		<a href="mailto:<?php echo $this->person['company']['email']; ?>?bcc=<?php echo $this->emailname; ?><?php echo $this->person['company']['id']; ?>a<?php echo $this->profile->id; ?>@<?php echo $this->emaildomain; ?>">
		                            			<?php  echo $this->person['company']['email']; ?> 
		                            		</a>
		                            		<span><?php echo $this->translate('email')?></span>
		                            	</li>
		                            <?php endif;?>
		                            <?php if(isset($this->person['company']['address']) && $this->person['company']['address']):?>
		                            	<li class="email"><?php echo $this->person['company']['address']; ?> <span><?php echo $this->translate('address')?></span></li>
		                            <?php endif;?>
		                            <?php if(isset($this->person['company']['website']) && $this->person['company']['website']):?>
		                            	<li class="website">
			                            	<a target="_blank" href="http://<?php echo $this->person['company']['website']; ?>">
			                            		<?php echo $this->person['company']['website']; ?> 
			                            	</a>
		                            		<span>
		                            			<?php echo $this->translate('website')?>
		                            		</span>
		                            	</li>
		                            <?php endif;?>
                                </ul>
                        </div>
                    </div>

                </section>

                <!-- Main Section End -->
<script type="text/javascript">
$(function(){
	addToLastviewed(0, <?php echo $this->person['id']?>);
	
	var data = new Object();
	data.count = 1;
	data.location = 'personrecord';
	data.id = <?php echo $this->person['id']?>;

	
	$('.gimmimoar').mouseover(
		function(){
			data =  addNotesC(data);
		}
	);

	$(window).scroll(function() {   
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 10) {
			 data =  addNotesC(data);
		   }
	});

	$('#google_maps_address').gmap3(
			{
				 map: {
				    options: {
				      maxZoom: 14 
				    }  
				 },
				 marker:{
				    address: <?php echo Zend_Json::encode($this->person['address']);?>,//company['company']['0'].country+' '+company['company']['0'].city+' '+ company['company']['0'].address,
				    options: {
				     icon: new google.maps.MarkerImage(
				       "/images/icons/arrow_down.png",
				       new google.maps.Size(32, 37, "px", "px")
				     )
				    }
				 }
				},
				"autofit" 
	);

	
});

function addTaskP()
{	
	
	var sdata = new Object();
	sdata.id_person = '<?php echo $this->person['id']; ?>';
	sdata.name = $('input#tasknameP').val();
	sdata.owner = $('select#ownerP').val();
	sdata.due = $('input#taskdueP').val();
	sdata.cat = $('select#taskCatP').val();
	sdata.publ = 1;
	if(sdata.name != '' && sdata.due != "" && sdata.cat != "")
	{
		$.sajax("/task/add",sdata, function(newdata){
			if(newdata.id){
				$('.popupballoon').fadeOut(); 
			}
			
		});
	};
};




</script>
<script type="text/javascript"src="/js/gmap3.js"></script>
<script type="text/javascript"src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>